src/views/projects/ProjectCreate.vue
src/views/projects/projects.vue

Fix: redirected user to project home when user click the access the project button

---

README.md

Reverts Ilhasoft/weni-webapp#188

Revert "Feature/test ci"

---

README.md

Reverts Ilhasoft/weni-webapp#195

Revert "feat: made changes to test the automatic deploy"

---

src/app.vue
src/components/ExternalSystem.vue
src/components/dashboard/news.vue
src/components/external/ProjectSelect.vue
src/components/external/Sidebar.vue
src/components/external/navbar.vue
src/components/orgs/orgList.vue
src/components/projects/ProjectList.vue
src/components/projects/ProjectListItem.vue
src/router.js
src/views/accountConfirm.vue
src/views/org/createOrg.vue
src/views/projects/ProjectCreate.vue
src/views/projects/projects.vue

Co-authored-by: Matheus Martins Sarmento <matheusm@users.noreply.github.com>

Improved route mapping

---

src/api/orgs.js
src/components/billing/Card.vue
src/components/billing/Modal.vue
src/components/billing/ModalPrice.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/store/billing/actions.js
src/store/billingSteps/index.js
src/views/billing/createOrg.vue

Co-authored-by: Matheus Martins Sarmento <matheusm@users.noreply.github.com>

feat: integrated billing pricing

---

src/components/orgs/orgListItem.vue
src/views/billing/tabs/invoices.vue
src/views/projects/projects.vue

Reverts Ilhasoft/weni-webapp#338

Restore billing access

---

src/views/billing/tabs/activeContactsDocDefinition.js

Co-authored-by: Matheus Martins Sarmento <matheusm@users.noreply.github.com>

feat: adjusted dimensions in active contacts doc definition

---

src/components/external/navbar.vue
src/locales/translations.json

feat: added weni community

---

src/components/ListOrdinator.vue
src/components/orgs/orgList.vue
src/locales/translations.json
src/views/org/orgs.vue
src/views/projects/projects.vue

Commit equivalent to #596 and #597.

feat: added commits from org list filter and ordering feature

---

src/components/KnowUserModal/Steps/About.vue

* Added phone rule to verify is phone inserted has invalid pattern

feat: added phone role for pattern phone

---

src/components/banners/ChatsInvitation.vue
src/views/home.vue

* Separated chats invitation into a new component;
* Design reviewed.

feat: added chats invitation into a new component

---

src/components/ListOrdinator.vue
src/components/orgs/OrgCard.vue

Design Review #1: Feature/orgs list redesign

---

src/api/orgs.js
src/components/orgs/orgList.vue
src/store/org/actions.js
src/store/org/state.js
src/views/org/orgs.vue

* Replaced org list to v2 endpoint wich is using the next cursor.

feat: replaced org list to v2 endpoint

---

src/store/project/actions.js

Wait untill flow_organization be filled.

feat: waited till flow organization be created

---

src/utils/ProjectDescriptionChanges.js

Fixed project description manager delay when org has so many projects.

fix: project description manager delay when org has so many projects

---

src/main.js

Redirect to Chats in case user access the Weni Platform from a small screen with touch feature.

feat: added Chats redirect if user is accessing from a mobile device

---

nginx.conf

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Images and files from Amazon S3 wasn't opening.
Adds Amazon domain to CSP settings.

[Nexus-1186] Adds Amazon S3 in Content Security Policy

---

src/locales/translations.json

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Need for new events in the recent activities tab.
Added translations for flows and AI delete actions.

[ENGAGE-868] - Added Flow and IA deletions to latest activities

---

tests/unit/unit/setup.js
tests/unit/unit/views/__snapshots__/home.spec.js.snap
tests/unit/unit/views/projects/__snapshots__/projects.spec.js.snap

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Mocks vue-qr-code-component and vue-stripe packages.

[Nexus-1414] Mocks Vue-QRCode-component and Vue-stripe Packages

---

package.json
src/app.vue
src/components/ExternalSystem.vue
src/components/SidebarModal.vue
src/components/external/Sidebar.vue
src/locales/translations.json
src/router.js
yarn.lock

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Add Insights Module

[ENGAGE-978] - Add Insights Module

---

src/components/external/Sidebar.vue

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Clarifies to the user that Brain is still an experimental module.
* Adds Beta tag to Brain sidebar option.

[Nexus-1537] Brain: Beta Tag

---

nginx.conf
src/app.vue
src/components/ApiOptions.vue
src/components/ExternalSystem.vue
src/locales/translations.json
src/main.js
src/router.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Nexus API viewer on APIs section;
* Adds bothub domain to frame list access on CSP.

[Nexus-1582] Nexus API Viewer

---

nginx.conf

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
When carrying out tests, we discovered that our configuration defined in Nginx had several headers missing and not configured. We then decided to implement the headers for analysis and correction in order to improve our security.
- [Design File 1](link_to_design_file_1)

add mapping for csp on nginx [CLOUD-1213]

---

nginx.conf

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
When carrying out tests, we discovered that our configuration defined in Nginx had several headers missing and not configured. We then decided to implement the headers for analysis and correction in order to improve our security.

[ENGAGE-1239] - Add mapping for csp on nginx

---

src/main.js
src/utils/plugins/Hotjar.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Monitoring by session replay using Hotjar.
Added Hotjar script at main.

[ENGAGE-1306] - Hotjar

---

src/components/external/Sidebar.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Unlock Insights for all users
- Changed the Insights module tag to `Beta`;
- Removed validation that limited the module to specific users.

[ENGAGE-1331] - Insights Beta

---

src/app.vue
src/main.js
src/utils/plugins/Hotjar.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
We need to know the email of which user hotjar is recording.
Init hotjar only after user email loaded and pass it to hotjar

[ENGAGE-1401] - Add user id at hotjar

---

src/views/register/index.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The onboarding flow does not close after the invited user has finished the process.
* Fixes the onboarding flow for invited users.

[Nexus-1871] Bug: Close Onboarding after Invited Users Submit

---

src/components/Sidebar/Sidebar.vue
src/components/common/RightBar/LearningCenter.vue
tests/unit/unit/components/common/RightBar/LearningCenter.spec.js

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Removes temporary the Champion Chatbot.

[Nexus-1903] Champion Chatbot: Removes Temporary

---

src/app.vue
src/components/Topbar/Topbar.vue
src/views/register/ModalCreateProjectSuccess.vue
src/views/register/index.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Fixes onboarding flow for new users;
* Hides temporarily the FAQ.

[Nexus-1934][Nexus-1936] Onboarding: Flow Correction for New User and Temporary Hiding of the FAQ

---

src/components/Sidebar/Sidebar.vue
src/components/Sidebar/SidebarOptionInside.vue
src/locales/translations.json
tests/unit/unit/components/Sidebar/SidebarOptionInside.spec.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- need new tag to Brain
Add New tag Brain
- [Design File](https://www.figma.com/design/9IZECUPFoL3erKMm4oJmz3/drafts-de-componentes?node-id=447-2394&m=dev)

[NEXUS-2017] - New tag Brain

---

src/api/brain.js
src/components/Sidebar/Sidebar.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
-  Add BrainOn nexus logic to tag
-  Add BrainOn nexus logic to tag

[Nexus 2017] - Add BrainOn nexus logic to tag

---

src/components/common/RightBar/ProjectUsers.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- add translation
- adding translations

[ENGAGE-1664] - Add pending translations to Permission project

---

docker-entrypoint.sh
src/app.vue
src/components/Sidebar/Sidebar.vue
src/components/SystemCommerce.vue
src/locales/translations.json
src/router.js
tests/unit/unit/components/Sidebar/Sidebar.spec.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds new Commerce module to Sidebar and Iframe;
* Adds access limitation for specific e-mails.

[RS-106] Commerce Module

---

src/components/SystemCommerce.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Prevents incorrect redirect to the Commerce module.

[RS-173] Bug: Commerce Module: Prevents Incorrect Redirect to the Commerce Module

---

src/components/Sidebar/Sidebar.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- unlock modules
- removing has_flow logic in sideBar component

[ENGAGE-1672] - Unlock modules if you don't have a flow created

---

src/components/users/permissionsObjects.js
tests/unit/components/users/permissionsObjects.spec.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Vue 3 migration.
Fixed i18n call in project user listing.

[CFE-381] - Hotfix project list users

---

src/locales/translations.json

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Vue 3 migration.
Adjusted crash translations.

[CFE-381] - Hotfix help view crash

---

src/components/common/RightBar/Notifications.vue
src/store/project/actions.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Vue 3 migration
Adjusted the pagination of recent activities in the topbar by separating the v-show from the v-for in the IntersectionObserver element.

[CFE-375] - Fix of topbar recent activities pagination

---

src/components/common/RightBar/NotificationsUpdates.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Removes the month descriptor on the Plataform Updates.

[RS-253] Platform Updates: Removes Month Descriptor

---

src/components/Sidebar/SidebarOption.vue
src/components/SystemIntelligences.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix brain iframe second load
- Changed v-if to v-show at iframe of brain;
- Adjusted SystemIntellingences load bothub iframe.

[NEXUS-2123] - Fix sidebar router

---

src/api/orgs.js
src/store/billing/actions.js
src/views/billing/tabs/activeContacts.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adjusting Billing report
- adding billing route

[ENGAGE-1858] Change billing report URL from Connect to Billing

---

package.json
yarn.lock

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Updating the unnic version to fix the bug mentioned [in this PR](https://github.com/weni-ai/unnnic/pull/599).
- Update Unnnic version.

[CFE-472] - Fix icons translate

---

src/utils/plugins/WebChat.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
With the fixed version of the Weni Web Chat, the CSP can use the calculated hash of the exact inline CSS content used in the Weni Web Chat to prevent use of the `usafe-inline`.
* Uses fixed version of the Weni Web Chat.

[HS-670] Fixed Version of the Weni Web Chat

---

src/views/billing/tabs/activeContacts.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
improves visualization in spreadsheets
- adjust logic csv render

[ENGAGE-1959] - adjust exportCSVByProject to break colunm URN

---

src/api/projects.js
src/app.vue
src/components/Topbar/ProfileDropdown.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
improving the flow of users coming from vtex
- add new v2 enpoint
- add logic to isVtexUsers
- adjusting profile render logic

[ENGAGE-2767] - Change render logic initial form data to vtex users

---

src/utils/transformIntoDraggableBubble.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
During the security process, Doris stopped working as expected.
* Uses style properties in a separated style tag;
* Removes Doris position when it is in fullscreen mode.

[HS-774] Doris: Style Adjustments

---

package-lock.json
package.json

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- update unnnic
- update unnnic

[ENGAGE-2963] Update unnnic version

---

src/components/ExternalSystem.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The Flows module sometimes requires the user to reauthenticate if their session was expired when trying to login into it.
Added the `authenticationRequired` event handler from child iframes, that logouts users automatically redirecting to the login page.

Modify Flows modules Iframe authentication

---

src/components/ExternalSystem.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- resolve problem redirect
- resolve problem redirect

Fix: Router flows

---

package-lock.json
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
To protect ourselves against XSS attacks, an update was made to Unnnic, which will be tested in this project initially. Therefore, the version of Unnnic used in this PR is not a stable version.
- Added Unnnic pre release version to test XSS security
https://github.com/user-attachments/assets/1cd2ba4a-37f4-455f-b1af-035627f14f0b

[CFE-558] - Added Unnnic pre release version to test XSS security

---

src/components/billing/WarningMaxActiveContacts.vue

* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Duplicated code in WarningMaxActiveContacts template
Refactored the template to use computed properties instead

refactor: Simplify WarningMaxActiveContacts component

---

src/components/billing/Card.vue
src/components/billing/ModalAddCreditCard.vue
src/store/billingSteps/actions.js
src/store/billingSteps/mutations.js

* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Improved store state management
Avoided direct state mutations by using actions, added default value for props

Refactor: Billing components store access

---

src/components/accounts/AccountPreferences.vue
src/components/accounts/AccountVerifyTwoFactorsSteps/AccountDownload2FAApp.vue
src/store/account/actions.js
src/store/account/mutations.js

* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Improved store state management
Avoided direct state mutations by using actions, added default value for props

Refactor: Accounts components direct state mutation

---

Dockerfile

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Adds old file fix
- [Design File 1](link_to_design_file_1)

fix-hotjar

---

src/components/ExternalSystem.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add new event to others modules get values
- add new event

[ENGAGE-3270] Add new event getIsCommerce

---

src/components/SystemIntelligences.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The agent builder module routes have changed and adjustments were needed here.
Updated pathname logic in SystemIntelligences whatSystem method

[NEXUS-2903] - Update pathname logic in SystemIntelligences whatSystem method

---

src/main.js

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other

fix: update Sentry environment configuration to use getEnv function

---

CHANGELOG.md

* * [ ] Bugfix
* * [ ] Tests
* * [X] Other

chore: Add CHANGELOG.md file to document version history

---

src/utils/plugins/i18n.js

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- resolve problems with translations on plataform 1.5
- adjust deepMerge logic

[ENGAGE-4077] adjusting deepMerge logic

---

src/views/register/ModalCreateProjectSuccess.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other

fix: use name instead of path to AB routing

---

src/api/orgs.js
src/app.vue
src/components/billing/WarningMaxActiveContacts.vue
src/store/billing/actions.js
tests/unit/unit/components/billing/WarningMaxActiveContacts.spec.js

* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Removed version log and no longer used request for max active contacts

fix: Remove no longer used active contacts request and version log

---

src/components/common/RightBar/Index.vue
src/components/common/RightBar/updateOrg.vue
tests/unit/unit/components/common/RightBar/UpdateOrg.spec.js

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Since lodash was not being imported, every org delete received an error modal
- Imported lodash to solve refereError
- Improved org removal functionality to remove it from the state list and close the rightBar component

fix: org delete error

---

tests/unit/unit/components/common/RightBar/UpdateOrg.spec.js

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Fix CI
Added lodash filter mock

test(UpdateOrg.spec): mock lodash filter function for unit tests

---

src/components/Topbar/ProfileDropdown.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix z-index to profile dropdown
Fix z-index to profile dropdown
Bug to solve:

Hotfix: Add z-index to profile dropdown

---

CHANGELOG.md
src/components/ExternalSystem.vue

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Allow autoplay in chat iframe
- Add autoplay param in chats iframe

[ENGAGE-4964] Add autoplay permission for autoplay in ExternalSystem component

---

src/components/Sidebar/Sidebar.vue
tests/unit/unit/components/Sidebar/Sidebar.spec.js

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Only moderators and contributors can access the bulkSend module
Updated module display permission

fix: permission handling for Bulk Send module in Sidebar

---

CHANGELOG.md

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Update CHANGELOG for version 2.16.1

Update CHANGELOG for version 2.17.0
